"""Fix upvotes_count default value

Revision ID: 89bda991b3cc
Revises: 7d0470271458
Create Date: 2025-12-05 23:59:14.042376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89bda991b3cc'
down_revision: Union[str, Sequence[str], None] = '7d0470271458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('upvote_count', sa.Integer(), server_default='0', nullable=False))
    op.drop_column('notes', 'upvote_counter')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('upvote_counter', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('notes', 'upvote_count')
    # ### end Alembic commands ###
