"""Fix note model with course_id

Revision ID: 9b43453905ef
Revises: f1e2d673d554
Create Date: 2025-12-05 23:45:52.538507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b43453905ef'
down_revision: Union[str, Sequence[str], None] = 'f1e2d673d554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('course_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('notes_created_by_fkey'), 'notes', type_='foreignkey')
    op.create_foreign_key(None, 'notes', 'courses', ['course_id'], ['id'])
    op.drop_column('notes', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.create_foreign_key(op.f('notes_created_by_fkey'), 'notes', 'courses', ['created_by'], ['id'])
    op.drop_column('notes', 'course_id')
    # ### end Alembic commands ###
