"""Fix upvotes_count default value

Revision ID: b2df7cd6cf1d
Revises: 2e2fdce8baed
Create Date: 2025-12-05 23:50:29.505832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2df7cd6cf1d'
down_revision: Union[str, Sequence[str], None] = '2e2fdce8baed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'upvote_counter',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'upvote_counter',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
